"""Generate a runnable Python script from a MethodSpec.

The generated script:
- Documents prerequisites and environment requirements
- Runs install commands via subprocess
- Runs the method's run commands via subprocess
- Prints a JSON result on stdout (suitable for agent consumption)
"""
from __future__ import annotations

import textwrap

from scientia.models import MethodSpec


def generate_executable_script(method_spec: MethodSpec) -> str:
    """Return a Python script (as a string) that installs and runs *method_spec*.

    The script is self-contained: it can be written to disk and executed
    with ``python3 <script>.py``.
    """
    name = method_spec.name
    prereqs = method_spec.prerequisites
    install_cmds = method_spec.install_commands
    run_cmds = method_spec.run_commands
    env = method_spec.env_spec

    # Build prerequisite block
    prereq_lines: list[str] = []
    if prereqs:
        prereq_lines.append("    # Prerequisites:")
        for p in prereqs:
            prereq_lines.append(f"    #   {p}")
    if env.python_version:
        prereq_lines.append(f"    # Requires Python {env.python_version}")
    if env.gpu_required:
        prereq_lines.append("    # GPU (CUDA) required — ensure a CUDA-capable device is available.")
    prereq_block = "\n".join(prereq_lines) if prereq_lines else "    # No explicit prerequisites listed."

    # Build install block
    if install_cmds:
        install_lines = [
            f"        subprocess.run({cmd!r}, shell=True, check=True)"
            for cmd in install_cmds
        ]
        install_block = "\n".join(install_lines)
    else:
        install_block = "        pass  # No install commands"

    # Build run block
    if run_cmds:
        run_lines = [
            f"        result = subprocess.run({cmd!r}, shell=True, capture_output=True, text=True)"
            for cmd in run_cmds
        ]
        # Collect outputs
        collect_lines = [
            "        outputs.append({",
            f"            \"command\": {run_cmds[0]!r},",
            "            \"returncode\": result.returncode,",
            "            \"stdout\": result.stdout.strip(),",
            "            \"stderr\": result.stderr.strip(),",
            "        })",
        ]
        if len(run_cmds) == 1:
            run_block = run_lines[0] + "\n" + "\n".join(collect_lines)
        else:
            # Multiple commands — loop pattern
            run_block_parts = []
            for i, cmd in enumerate(run_cmds):
                run_block_parts.append(
                    f"        result_{i} = subprocess.run({cmd!r}, shell=True, capture_output=True, text=True)"
                )
                run_block_parts.append(
                    f"        outputs.append({{'command': {cmd!r}, 'returncode': result_{i}.returncode, "
                    f"'stdout': result_{i}.stdout.strip(), 'stderr': result_{i}.stderr.strip()}})"
                )
            run_block = "\n".join(run_block_parts)
    else:
        run_block = "        pass  # No run commands"

    # Dependencies from env_spec (for documentation)
    deps_comment = ""
    if env.dependencies:
        deps_comment = "    # Known dependencies: " + ", ".join(env.dependencies)

    script = textwrap.dedent(f"""\
        #!/usr/bin/env python3
        \"\"\"Executable skill script for: {name}

        Auto-generated by Scientia executable_generator.
        Runs install commands then the method's run commands, printing JSON to stdout.
        \"\"\"
        from __future__ import annotations
        import json
        import subprocess
        import sys


        def check_prerequisites() -> None:
        {prereq_block}
        {deps_comment}
            pass


        def install() -> None:
            \"\"\"Run install commands for {name}.\"\"\"
        {install_block}


        def run() -> list[dict]:
            \"\"\"Run the method and return a list of command results.\"\"\"
            outputs: list[dict] = []
        {run_block}
            return outputs


        def main() -> None:
            check_prerequisites()

            result = {{
                "skill": {name!r},
                "status": "ok",
                "install": [],
                "outputs": [],
            }}

            try:
                install()
                result["install"] = {[c for c in install_cmds]!r}
            except subprocess.CalledProcessError as exc:
                result["status"] = "install_failed"
                result["error"] = str(exc)
                print(json.dumps(result))
                sys.exit(1)

            try:
                result["outputs"] = run()
            except Exception as exc:
                result["status"] = "run_failed"
                result["error"] = str(exc)
                print(json.dumps(result))
                sys.exit(1)

            print(json.dumps(result, indent=2))


        if __name__ == "__main__":
            main()
        """)
    return script
